server:
  error.whitelabel.enabled: false
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none # disabled because of flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
      javax:
        persistence:
          query:
            timeout: 10000
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: V3__create_tables.sql
  datasource:
    url: jdbc:postgresql://bismarck:5432/bayes?ssl=true&sslmode=require
    username: bayes
    password: bayes
  flyway:
    enabled: true
    user: bayes
    password: bayes
  banner:
    image:
      location: classpath:banner.png
      width: 100
      height: 15
      margin: 1

logging:
  config: classpath:logback-${ENV:development}.xml
